name: Runing dummy test

on:
    push: 
        branches: [master, main, develop]
    pull_request: 
        branches: [master, main, develop]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
           - uses: actions/checkout@v2
           - uses: actions/setup-node@v2
             with:
                node-version: 18
           - run: npm ci

             
            
            